services:
  stratege-ai:
    build: /host-home/Stratege-IA
    volumes:
      - /host-home/Stratege-IA/saved_model:/saved_model
      - /host-home/Stratege-IA/h5:/h5
    environment:
      START_EPISODE: 9100
      NB_EPISODES: 1000000
    logging:
      options:
        max-size: "10m"
        max-file: "5"
